import assert from 'node:assert/strict';
import { createHash, randomBytes, randomUUID } from 'node:crypto';
import { mkdir } from 'node:fs/promises';
import postgres from 'postgres';
import { serve } from '@hono/node-server';
import { chromium, type Browser } from 'playwright';
import { createApp } from '../src/app.js';
import { connectDatabase } from '../src/db/client.js';
import { migrate } from '../src/db/migrate.js';
import { CollaborationService } from '../src/domain/service.js';
import type { Credential } from '../src/config.js';
import type { Change, claims } from '../src/db/schema.js';

if (!process.env.DATABASE_URL) throw new Error('DATABASE_URL required');
const schema = `planning_ui_${randomUUID().replaceAll('-', '')}`;
const admin = postgres(process.env.DATABASE_URL, { max: 1, onnotice: () => {} });
await admin.unsafe(`CREATE SCHEMA "${schema}"`);
const connection = connectDatabase(process.env.DATABASE_URL, schema);
const service = new CollaborationService(connection.db);
const repo = `planning-ui/${randomUUID()}`, token = randomBytes(32).toString('hex');
const human = { member: 'lead', role: 'human' as const, repo }, agent = { member: 'alice', role: 'agent' as const, repo };
const credentials: Credential[] = [{ ...human, token_hash: createHash('sha256').update(token).digest('hex'), expires_at: new Date(Date.now() + 3600000).toISOString() }];
const server = serve({ fetch: createApp({ service, credentials: () => credentials }).fetch, hostname: '127.0.0.1', port: 0 });
if (!server.listening) await new Promise<void>(resolve => server.once('listening', resolve));
const address = server.address(); assert(address && typeof address !== 'string');
let browser: Browser | undefined;
try {
  await migrate(process.env.DATABASE_URL, schema);
  browser = await chromium.launch({ headless: true, executablePath: process.env.PREFLIGHT_CHROMIUM_PATH });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto(`http://127.0.0.1:${address.port}`);
  await page.locator('#login-panel').waitFor({ state: 'visible' });
  await page.locator('#token').fill(token); await page.getByRole('button', { name: '连接团队' }).click();
  await page.locator('#board').waitFor({ state: 'visible' });
  assert(await page.locator('#new-goal').isDisabled(), 'Fresh workspace must first create a project');
  await page.locator('#new-project').click();
  const unsafeTitle = '"/><img src=x onerror=alert(1)> Release';
  await page.locator('#manage-heading').waitFor();
  await page.locator('#manage-form input[name=title]').fill(unsafeTitle);
  await page.locator('#manage-description').fill('Release boundary');
  await page.locator('#manage-planning_agents').fill('alice');
  await page.locator('#manage-form .primary').click(); await page.locator('#manage-dialog').waitFor({ state: 'hidden' });
  const p = (await service.project(human)).projects[0]; assert(p);
  await page.locator('#project-select').selectOption(p.id);
  await page.locator('#edit-project').waitFor({ state: 'visible' });
  await page.waitForFunction(() => !document.querySelector<HTMLButtonElement>('#new-milestone')!.disabled);
  await page.locator('#edit-project').click();
  assert.equal(await page.locator('#manage-form input[name=title]').inputValue(), unsafeTitle);
  assert.equal(await page.locator('#manage-dialog img').count(), 0, 'Quoted values must not become HTML attributes');
  await page.locator('#close-manage').click();
  await page.locator('#new-milestone').click();
  await page.locator('#manage-form input[name=title]').fill('First release'); await page.locator('#manage-due_date').fill('2026-12-01');
  await page.locator('#manage-form .primary').click(); await page.locator('#manage-dialog').waitFor({ state: 'hidden' });
  await page.locator('#milestones').getByText('First release', { exact: true }).waitFor();
  const m = (await service.project(human, p.id)).milestones[0]; assert(m);
  await page.locator('#new-goal').click();
  await page.locator('#goal-title').fill('Login reliability'); await page.locator('#goal-objective').fill('Keep compatibility');
  await page.locator('#goal-acceptance').fill('Investigation complete\nRegression covered');
  await page.locator('#goal-state').selectOption('ready'); await page.locator('#goal-priority').selectOption('1');
  await page.locator('#goal-owner').fill('lead'); await page.locator('#goal-date').fill('2026-11-01'); await page.locator('#goal-milestone').selectOption(m.id);
  await page.locator('#goal-form .primary').click(); await page.locator('#goal-dialog').waitFor({ state: 'hidden' });
  await page.getByText('Login reliability', { exact: true }).waitFor();
  let g = (await service.project(human, p.id)).goals[0]!; assert(g); assert.equal(g.priority, 1); assert.equal(g.owner, 'lead');
  const addTask = async (title: string, index: number, dependency?: string) => {
    await page.locator(`[data-task-goal="${g.id}"]`).click(); await page.locator('#manage-form input[name=title]').fill(title);
    await page.locator('#manage-task_acceptance').fill(`${title} validated`); await page.locator(`input[name=criteria][value="${index}"]`).check();
    if (dependency) await page.locator('#manage-dependencies').selectOption([dependency]);
    await page.locator('#manage-form .primary').click(); await page.locator('#manage-dialog').waitFor({ state: 'hidden' });
    await page.getByText(title, { exact: true }).first().waitFor();
    const c = (await service.project(human, p.id)).changes.find(c => c.title === title); assert(c); return c;
  };
  const a = await addTask('Investigation', 0); const b = await addTask('Regression', 1, a.id);
  assert.match(await page.locator('#goals').innerText(), /等待依赖/);
  await page.locator('#work-view').selectOption('board'); assert(await page.locator('#goals').isHidden());
  assert.match(await page.locator('#task-board').innerText(), /阻塞 · 1/);
  assert.match(await page.locator('#task-board').innerText(), /Regression/);
  const work = await service.execute(agent, 'preflight_manage_claim', { request_id: randomUUID(), operation: 'claim', change_id: a.id, expected_version: a.version }) as { change: Change; session_id: string; claim: typeof claims.$inferSelect };
  await page.locator('#refresh').click(); await page.getByText('执行责任：alice', { exact: false }).first().waitFor();
  await page.locator('#work-view').selectOption('list');
  await page.locator(`[data-edit-task="${a.id}"]`).click();
  await page.locator('#manage-form .primary').click();
  await page.locator('#manage-dialog .dialog-error').waitFor(); assert.match(await page.locator('.dialog-error').innerText(), /lease/);
  await page.locator('#close-manage').click();
  // A planner can pause the plan; this rejects writes, but cannot stop an external process.
  await page.locator(`[data-edit-goal="${g.id}"]`).click(); await page.locator('#goal-state').selectOption('paused');
  await page.locator('#goal-form .primary').click(); await page.locator('#goal-dialog').waitFor({ state: 'hidden' });
  await page.getByText('目标暂停', { exact: false }).first().waitFor();
  await assert.rejects(service.execute(agent, 'preflight_report_progress', { request_id: randomUUID(), change_id: a.id, session_id: work.session_id, lease_id: work.claim.id, lease_epoch: work.claim.epoch, expected_version: work.change.version, status: 'implementing', summary: 'Cannot execute paused plan' }), (e: unknown) => e instanceof Error && 'code' in e && e.code === 'GOAL_NOT_READY');
  await page.locator('#plan-filter').selectOption('ready'); assert.equal(await page.locator('.goal-card').count(), 0);
  await page.locator('#plan-filter').selectOption('paused'); assert.equal(await page.locator('.goal-card').count(), 1);
  await page.locator(`[data-edit-goal="${g.id}"]`).click(); await page.locator('#goal-state').selectOption('ready');
  await page.locator('#goal-form .primary').click(); await page.locator('#goal-dialog').waitFor({ state: 'hidden' }); await page.locator('#plan-filter').selectOption('all');
  // Concurrent plan edits must display a conflict inside the dialog and preserve typed input.
  await page.locator(`[data-edit-goal="${g.id}"]`).click();
  g = (await service.project(human, p.id)).goals[0]!;
  await service.execute(human, 'preflight_manage_goal', { request_id: randomUUID(), goal_id: g.id, expected_version: g.version, priority: 2 });
  await page.locator('#goal-title').fill('Typed stale edit'); await page.locator('#goal-form .primary').click(); await page.locator('#goal-dialog .dialog-error').waitFor();
  assert.match(await page.locator('#goal-dialog .dialog-error').innerText(), /version/);
  assert.equal(await page.locator('#goal-title').inputValue(), 'Typed stale edit'); await page.locator('#close-goal').click();
  await page.locator('#refresh').click();
  await page.locator(`[data-edit-task="${b.id}"]`).click(); await page.locator('#manage-form input[name=title]').fill('Regression revised');
  await page.locator('#manage-form .primary').click(); await page.locator('#manage-dialog').waitFor({ state: 'hidden' }); await page.getByText('Regression revised', { exact: true }).first().waitFor();
  await service.execute(human, 'preflight_manage_milestone', { request_id: randomUUID(), operation: 'update', project_id: p.id, milestone_id: m.id, expected_version: m.version, state: 'archived' });
  await page.locator('#refresh').click();
  await page.locator('#milestones').getByText(/已归档/).waitFor();
  await page.locator(`[data-edit-goal="${g.id}"]`).click();
  assert.equal(await page.locator('#goal-milestone').inputValue(), m.id, 'Editing a goal must preserve its historical archived milestone');
  await page.locator('#goal-form .primary').click(); await page.locator('#goal-dialog').waitFor({ state: 'hidden' });
  assert.equal((await service.project(human, p.id)).goals[0]?.milestone_id, m.id);
  await mkdir('.preflight/screenshots', { recursive: true }); await page.screenshot({ path: '.preflight/screenshots/planning-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 }); await page.locator('#work-view').selectOption('board');
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Mobile planning board overflows');
  await page.screenshot({ path: '.preflight/screenshots/planning-mobile.png', fullPage: true });
  assert.equal(await page.locator('#board img, #board svg, #board script').count(), 0); assert.deepEqual(errors, []);
  await page.locator('#logout').click(); await page.locator('#login-panel').waitFor({ state: 'visible' });
  console.log('✓ Real Chromium: fresh project/delegation/milestone/goal/tasks/dependencies, list/board, live Agent responsibility, pause/filter/resume, leased-task edits rejected, conflict preserves input, quoted XSS escaping, mobile and logout');
} finally {
  await browser?.close(); await new Promise<void>(resolve => server.close(() => resolve())); await connection.client.end();
  await admin.unsafe(`DROP SCHEMA "${schema}" CASCADE`); await admin.end();
}
