import assert from 'node:assert/strict';
import { createHash, randomBytes, randomUUID } from 'node:crypto';
import postgres from 'postgres';
import { serve } from '@hono/node-server';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StreamableHTTPClientTransport } from '@modelcontextprotocol/sdk/client/streamableHttp.js';
import { createApp } from '../src/app.js';
import { connectDatabase } from '../src/db/client.js';
import { migrate } from '../src/db/migrate.js';
import { CollaborationService } from '../src/domain/service.js';
import type * as t from '../src/db/schema.js';
import type { Credential } from '../src/config.js';
const url = process.env.DATABASE_URL; if (!url) throw new Error('DATABASE_URL required');
const schema = `reliability_${randomUUID().replaceAll('-', '')}`, repo = `test/${randomUUID()}`;
const admin = postgres(url, { max: 1, onnotice: () => {} }); await admin.unsafe(`CREATE SCHEMA "${schema}"`);
const connection = connectDatabase(url, schema); let instant = Date.now();
const service = new CollaborationService(connection.db, () => new Date(instant));
const secrets = Array.from({ length: 4 }, () => randomBytes(32).toString('hex'));
const credentials: Credential[] = ['lead','alice','bob','foreign'].map((member,i) => ({ member, role: i===0 ? 'human' : 'agent', repo: i===3 ? repo+'/other' : repo, token_hash: createHash('sha256').update(secrets[i]!).digest('hex'), expires_at: new Date(Date.now()+3600000).toISOString() }));
const server = serve({ fetch: createApp({ service, credentials: () => credentials }).fetch, hostname: '127.0.0.1', port: 0 });
if (!server.listening) await new Promise<void>(r => server.once('listening', r));
const address = server.address(); assert(address && typeof address !== 'string');
const clients = credentials.map(c => new Client({ name: c.member, version: '1' })); const [lead,alice,bob,foreign] = clients as [Client,Client,Client,Client];
async function call<T>(c: Client, name: string, args: Record<string,unknown> = {}): Promise<T> {
  const read = ['preflight_get_project','preflight_get_context','preflight_get_updates','preflight_search_findings'].includes(name);
  const result = await c.callTool({ name, arguments: { ...(!read ? { request_id: randomUUID() } : {}), ...args } });
  if (result.isError) { const block = (result.content as { text: string }[])[0]!; throw new Error(JSON.parse(block.text).error.code); }
  return (result.structuredContent as { data: T }).data;
}
type Open = { session: { id: string }; runtime: typeof t.runtimes.$inferSelect };
type Work = { session_id: string; change: t.Change; claim: typeof t.claims.$inferSelect };
type Updates = { updates: { delivery_id: string; action: string; aggregate_id: string; entity_version: number }[] };
const identity = (s: Open) => ({ session_id: s.session.id, runtime_id: s.runtime.instance_id, runtime_epoch: s.runtime.epoch });
try {
  await migrate(url, schema); await migrate(url, schema);
  for (let i=0;i<clients.length;i++) await clients[i]!.connect(new StreamableHTTPClientTransport(new URL(`http://127.0.0.1:${address.port}/mcp`), { requestInit: { headers: { Authorization: `Bearer ${secrets[i]}` } } }));
  assert.equal((await alice.listTools()).tools.length,17);
  const { project: p } = await call<{ project: typeof t.projects.$inferSelect }>(lead,'preflight_manage_project',{ operation:'create',title:'Reliable project' });
  const a = await call<Open>(alice,'preflight_manage_session',{operation:'open',project_id:p.id,instance_id:randomUUID()});
  let b = await call<Open>(bob,'preflight_manage_session',{operation:'open',project_id:p.id,instance_id:randomUUID()});
  assert.equal((await call<Updates>(alice,'preflight_get_updates',identity(a))).updates.length,1);
  let { goal: g } = await call<{goal: typeof t.goals.$inferSelect}>(lead,'preflight_register_goal',{project_id:p.id,title:'Goal',objective:'Evidence',acceptance:['Evidence'],plan_state:'ready'});
  const first = await call<Updates>(bob,'preflight_get_updates',identity(b));
  assert(first.updates.some(u=>u.aggregate_id===g.id));
  assert.deepEqual(await call(bob,'preflight_get_updates',identity(b)),first);
  await assert.rejects(call(foreign,'preflight_get_updates',identity(b)),/RUNTIME_STALE/);
  await assert.rejects(call(alice,'preflight_ack_updates',{...identity(a),updates:[{delivery_id:first.updates[0]!.delivery_id,outcome:'handled'}]}),/DELIVERY_NOT_FOUND/);
  console.log('✓ 17 official SDK tools; empty sessions, project subscription, durable repeat delivery and owner/repository isolation');
  // Failure after business and audit writes must roll back the entire outbox transaction.
  await connection.client.unsafe(`CREATE FUNCTION reject_delivery() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'injected delivery failure'; END $$; CREATE TRIGGER reject_delivery BEFORE INSERT ON event_deliveries FOR EACH ROW EXECUTE FUNCTION reject_delivery()`);
  await assert.rejects(call(lead,'preflight_manage_goal',{goal_id:g.id,expected_version:g.version,priority:1}),/UPSTREAM_UNAVAILABLE/);
  assert.equal((await connection.client`SELECT version FROM goals WHERE id=${g.id}`)[0]!.version,g.version);
  await connection.client.unsafe('DROP TRIGGER reject_delivery ON event_deliveries; DROP FUNCTION reject_delivery()');
  ({goal:g}=await call<{goal: typeof g}>(lead,'preflight_manage_goal',{goal_id:g.id,expected_version:g.version,priority:1}));
  console.log('✓ Fault after domain mutation rolls back domain, audit, outbox and recipient inserts together');
  const old = b; instant+=120001; await service.maintain(); await service.maintain();
  const missing = await connection.client`SELECT * FROM domain_events WHERE action='runtime.unresponsive'`; assert.equal(missing.length,2);
  await assert.rejects(call(bob,'preflight_manage_session',{...identity(b),operation:'heartbeat'}),/RUNTIME_EXPIRED/);
  const recovered = await call<{runtime: typeof b.runtime}>(bob,'preflight_manage_session',{operation:'recover',session_id:b.session.id,instance_id:randomUUID(),expected_version:b.runtime.version}); b={...b,runtime:recovered.runtime};
  assert.equal(b.runtime.epoch,2); assert((await call<Updates>(bob,'preflight_get_updates',identity(b))).updates.some(u=>u.aggregate_id===g.id));
  await assert.rejects(call(bob,'preflight_ack_updates',{...identity(old),updates:[{delivery_id:first.updates[0]!.delivery_id,outcome:'handled'}]}),/RUNTIME_STALE/);
  await assert.rejects(call(bob,'preflight_manage_session',{operation:'recover',session_id:b.session.id,instance_id:randomUUID(),expected_version:b.runtime.version}),/RUNTIME_BUSY/);
  console.log('✓ Durable unacked updates survive recovery; old runtime epochs cannot ack or mutate; worker missing events fire once');
  const proposed = await call<Work>(bob,'preflight_start_work',{...identity(b),goal_id:g.id,title:'Task',agent_type:'SDK-test',mode:'claim',task_acceptance:['Evidence'],goal_criteria_indices:[0]});
  await assert.rejects(call(bob,'preflight_start_work',{...identity(b),goal_id:g.id,title:'Second',agent_type:'SDK-test',mode:'claim',task_acceptance:['Evidence'],goal_criteria_indices:[0]}),/SESSION_CAPACITY/);
  const request_id=randomUUID(), findings={...identity(b),request_id,change_id:proposed.change.id,findings:[{kind:'observation',content:'A durable finding',confidence:1}]};
  assert.deepEqual(await call(bob,'preflight_publish_findings',findings),await call(bob,'preflight_publish_findings',findings));
  ({goal:g}=await call<{goal: typeof g}>(lead,'preflight_manage_goal',{goal_id:g.id,expected_version:g.version,plan_state:'paused'}));
  const updates=(await call<Updates>(bob,'preflight_get_updates',identity(b))).updates;
  const stop=updates.find(u=>u.aggregate_id===g.id && u.entity_version===g.version)!; assert(stop);
  await call(bob,'preflight_manage_session',{...identity(b),operation:'heartbeat',state:'running'});
  await assert.rejects(call(bob,'preflight_ack_updates',{...identity(b),updates:[{delivery_id:stop.delivery_id,outcome:'stopped'}]}),/STOP_NOT_OBSERVED/);
  await call(bob,'preflight_manage_session',{...identity(b),operation:'heartbeat',state:'waiting'});
  await call(bob,'preflight_ack_updates',{...identity(b),updates:[{delivery_id:stop.delivery_id,outcome:'stopped',observed_version:g.version}]});
  const board=await call<Awaited<ReturnType<CollaborationService['project']>>>(lead,'preflight_get_project',{project_id:p.id});
  assert(board.reliability.stop_controls.some(c=>c.outcome==='stopped')); assert.equal(board.goals[0]!.progress,'paused');
  console.log('✓ Controlled capacity, business retry, pause feedback requires idle runtime; planned pause is separate from adapter stop report');
  ({goal:g}=await call<{goal: typeof g}>(lead,'preflight_manage_goal',{goal_id:g.id,expected_version:g.version,plan_state:'ready'}));
  const {decision}=await call<{decision: typeof t.decisions.$inferSelect}>(bob,'preflight_propose_decision',{...identity(b),change_id:proposed.change.id,question:'Pick mechanism',context:'Within goal',category:'unknown',urgency:'blocking',options:[{label:'A',description:'A'},{label:'B',description:'B'}]});
  assert(decision.round_deadline_at); instant+=600001; await service.maintain(); await service.maintain();
  const [timed]=await connection.client`SELECT * FROM decisions WHERE id=${decision.id}`;
  assert.equal(timed!.status,'deferred');assert.equal(timed!.deferred_reason,'unanswered_timeout');assert.equal(timed!.review_round,1);
  assert.equal((await connection.client`SELECT * FROM domain_events WHERE aggregate_id=${decision.id} AND action='decision.deferred'`).length,1);
  assert.equal((await connection.client`SELECT release_reason FROM work_claims WHERE id=${proposed.claim.id}`)[0]!.release_reason,'expired');
  await assert.rejects(call(bob,'preflight_publish_findings',findings),/RUNTIME_EXPIRED/);
  console.log('✓ Persisted deadline fires without reviews, stays one round, emits once; lease expiry runs without claim attempts; stale retries are fenced');
} finally {
  await Promise.allSettled(clients.map(c=>c.close())); await new Promise<void>(r=>server.close(()=>r()));
  await connection.client.end({timeout:2});await admin.unsafe(`DROP SCHEMA "${schema}" CASCADE`);await admin.end({timeout:2});
}
